STANDARDIZED_CATEGORIES = frozenset({
    "CRYPTO", "POLITICS", "SPORTS", "ECONOMICS", "ENTERTAINMENT",
    "SCIENCE", "TECHNOLOGY", "WEATHER", "LEGAL", "OTHER",
})

DEFAULT_CANONICALIZE_BATCH_SIZE = 15
DEFAULT_BULK_CREATE_BATCH_SIZE = 200

DEFAULT_MIN_CONFIDENCE = 0.70

DEFAULT_RESOLUTION_LOOKBACK_DAYS = 3
# How long after a listing is deactivated the settle cycle keeps looking for its final value; disputed results can
# take days to settle.
DEFAULT_SETTLEMENT_LOOKBACK_DAYS = 30
# Outcomes each exchange looks up per settle cycle, so a backlog can't hold up the fetch loop for long.
DEFAULT_SETTLE_MAX_CANDIDATES = 20_000



DEFAULT_MAX_MESSAGES = 500
DEFAULT_MAX_WAIT_SECONDS = 60
DEFAULT_NOTIFY_MAX_WAIT_SECONDS = 300
DEFAULT_VISIBILITY_TIMEOUT = 900

DEFAULT_CANONICALIZE_MODEL = "claude-haiku-4-5-20251001"
DEFAULT_SEMANTIC_JUDGMENT_MODEL = "claude-sonnet-4-6"
DEFAULT_VOYAGE_EMBEDDING_MODEL = "voyage-3"

DEFAULT_EMBEDDING_SIMILARITY_THRESHOLD = 0.85
DEFAULT_HEDGEABLE_WITH_CONFIDENCE = 0.90

DEFAULT_SYNC_THRESHOLD = 10
DEFAULT_NEIGHBOR_SEARCH_LIMIT = 60
DEFAULT_VOYAGE_EMBED_CHUNK_SIZE = 2000
DEFAULT_STALE_MISS_THRESHOLD = 6
# A fetch returning fewer than this share of an exchange's tracked events is treated as an outage, not closures.
DEFAULT_STALE_MIN_FEED_RATIO = 0.5

DEFAULT_FETCH_MAX_SQS_MESSAGES = 100000
DEFAULT_RESOLVE_MAX_SQS_MESSAGES = 100000
DEFAULT_STALE_MAX_SQS_MESSAGES = 100000
DEFAULT_NOTIFY_MAX_MESSAGES = 100000

DEFAULT_FETCH_INTERVAL_SECONDS = 60
DEFAULT_RESOLVE_INTERVAL_SECONDS = 1800
DEFAULT_STALE_INTERVAL_SECONDS = 3600
DEFAULT_SETTLE_INTERVAL_SECONDS = 900

# 24h dollar volume an event needs before it is ingested; every adapter reports 24h volume.
DEFAULT_MIN_EVENT_VOLUME: float | None = 1000
