STANDARDIZED_CATEGORIES = frozenset({
    "CRYPTO", "POLITICS", "SPORTS", "ECONOMICS", "ENTERTAINMENT",
    "SCIENCE", "TECHNOLOGY", "WEATHER", "LEGAL", "OTHER",
})

DEFAULT_CANONICALIZE_BATCH_SIZE = 15
DEFAULT_BULK_CREATE_BATCH_SIZE = 200

DEFAULT_DEDUP_EXPIRY_TOLERANCE_HOURS = 1

DEFAULT_MIN_CONFIDENCE = 0.70

DEFAULT_RESOLUTION_LOOKBACK_DAYS = 3



DEFAULT_MAX_MESSAGES = 500
DEFAULT_MAX_WAIT_SECONDS = 60
DEFAULT_NOTIFY_MAX_WAIT_SECONDS = 300
DEFAULT_VISIBILITY_TIMEOUT = 900

DEFAULT_CANONICALIZE_MODEL = "claude-haiku-4-5-20251001"
DEFAULT_SEMANTIC_JUDGMENT_MODEL = "claude-sonnet-4-6"
DEFAULT_VOYAGE_EMBEDDING_MODEL = "voyage-3"

DEFAULT_EMBEDDING_SIMILARITY_THRESHOLD = 0.85
DEFAULT_HEDGEABLE_WITH_CONFIDENCE = 0.90

DEFAULT_SYNC_THRESHOLD = 10
DEFAULT_NEIGHBOR_SEARCH_LIMIT = 60
DEFAULT_VOYAGE_EMBED_CHUNK_SIZE = 2000
DEFAULT_STALE_MISS_THRESHOLD = 6

DEFAULT_FETCH_MAX_SQS_MESSAGES = 100000
DEFAULT_RESOLVE_MAX_SQS_MESSAGES = 100000
DEFAULT_STALE_MAX_SQS_MESSAGES = 100000
DEFAULT_NOTIFY_MAX_MESSAGES = 100000

DEFAULT_FETCH_INTERVAL_SECONDS = 60
DEFAULT_RESOLVE_INTERVAL_SECONDS = 1800
DEFAULT_STALE_INTERVAL_SECONDS = 3600

DEFAULT_MIN_EVENT_VOLUME: float | None = 5000
